version: "3.1"

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy-network
    ports:
      - 80:80
    depends_on:
      - weatherapp-backend
      - weatherapp-frontend

  weatherapp-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: weatherapp-frontend
    container_name: weatherapp-frontend
    ports:
      - 5000:5000
    depends_on:
      - weatherapp-backend
    networks:
      - proxy-network

  weatherapp-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: weatherapp-backend
    container_name: weatherapp-backend
    environment:
      APPID: "${APPID}"
      PORT: 8080
    ports:
      - 8080:8080
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
