version: "3.1"

services:

  weatherapp-frontend-dev:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    command: npm start
    image: weatherapp-frontend-dev
    container_name: weatherapp-frontend-dev
    environment:
      ENDPOINT: "http://localhost:9000/api"
      CHOKIDAR_USEPOLLING: "true" # Fixes hot reload on Windows when using WSL
    ports:
      - 8000:8000
    volumes:
      - ./frontend/:/usr/src/app
      - node_modules_front:/usr/src/app/node_modules
    depends_on:
      - weatherapp-backend-dev

  weatherapp-backend-dev:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    command: npm run dev
    image: weatherapp-backend-dev
    container_name: weatherapp-backend-dev
    environment:
      APPID: "${APPID}"
      CHOKIDAR_USEPOLLING: "true" # Fixes hot reload on Windows when using WSL
    ports:
      - 9000:9000
    volumes:
      - ./backend/:/usr/src/app
      - node_modules_back:/usr/src/app/node_modules

volumes:
  node_modules_front:
  node_modules_back: