version: "3.1"

services:

  weatherapp_frontend:
    build: frontend/.
    image: weatherapp_frontend
    environment:
      ENDPOINT: "http://localhost:9000/api"
    ports:
      - 8000:8000
    depends_on:
      - weatherapp_backend

  weatherapp_backend:
    build: backend/
    image: weatherapp_backend
    environment:
      APPID: "${APPID}"
    ports:
      - 9000:9000

