version: "3.1"
services:
  reverse-proxy:
    image: nginx
    restart: unless-stopped
    volumes:
      - /src/weatherapp/nginx.conf:/etc/nginx/nginx.conf
      - /src/data/certbot/conf:/etc/letsencrypt
      - /src/data/certbot/www:/var/www/certbot
    networks:
      - proxy-network
    ports:
      - 80:80
      - 443:443
    depends_on:
      - weatherapp-backend
      - weatherapp-frontend

  weatherapp-frontend:
    image: osholopa/weatherapp-frontend:latest
    restart: unless-stopped
    container_name: weatherapp-frontend
    ports:
      - 5000:5000
    depends_on:
      - weatherapp-backend
    networks:
      - proxy-network

  weatherapp-backend:
    image: osholopa/weatherapp-backend
    restart: unless-stopped
    container_name: weatherapp-backend
    environment:
      APPID: "${APPID}"
      PORT: 8080
    ports:
      - 8080:8080
    networks:
      - proxy-network

  certbot:
    image: certbot/certbot
    volumes:
      - /src/data/certbot/conf:/etc/letsencrypt
      - /src/data/certbot/www:/var/www/certbot
networks:
  proxy-network: